### ISSUE TITLE
scandit-engine-sdk.min.js [Uncaught TypeError: Failed to construct 'URL': Invalid URL]

### ISSUE THREAD

**Issue by morganjury** [Scandit/barcodescanner-sdk-for-web-samples#2]
Hi all,

I'm using the scandit-sdk/example.html file using the options:
<script src="https://unpkg.com/scandit-sdk"></script>
engineLocation: "https://unpkg.com/scandit-sdk/build"

When I load the webpage I am prompted to allow camera access the page looks like it should work but swiftly get a message in the console which reads:

Uncaught TypeError: Failed to construct 'URL': Invalid URL
    at Array.ASM_CONSTS (https://unpkg.com/scandit-sdk@2.1.0/build/scandit-engine-sdk.min.js:1:53979)
    at _emscripten_asm_const_ii (https://unpkg.com/scandit-sdk@2.1.0/build/scandit-engine-sdk.min.js:1:11727)
    at wasm-function[2492]:391
    at wasm-function[1891]:15
    at Object.Module.dynCall_vii (https://unpkg.com/scandit-sdk@2.1.0/build/scandit-engine-sdk.min.js:1:142559)
    at invoke_vii (https://unpkg.com/scandit-sdk@2.1.0/build/scandit-engine-sdk.min.js:1:34284)
    at wasm-function[2493]:513
    at wasm-function[1888]:19
    at Object.Module.dynCall_viiii (https://unpkg.com/scandit-sdk@2.1.0/build/scandit-engine-sdk.min.js:1:144262)
    at invoke_viiii (https://unpkg.com/scandit-sdk@2.1.0/build/scandit-engine-sdk.min.js:1:36772)

The file appears to be building a URL object which I see nothing immediately wrong with...have I missed something?

Thanks

**Comment by Shyiy** [comment]
Hello there,

The issue is most probably caused by you accessing the example.html file directly by simply opening it as a file in your file system (resulting in it appearing with a file:/// URL in the browser).

As documented under [https://docs.scandit.com/stable/web/index.html#example-application](https://docs.scandit.com/stable/web/index.html#example-application) while testing you should serve the application via any kind local web server to ensure that a normal URL is used in your browser.

(obviously this will not be an issue once you access your application online)

I hope this sets you on the right track!
